server:
  port: 8989
  servlet:
    context-path: /files

spring:
  application:
    name: files
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/filemanagement?characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/com/lijinghai/mapper/*.xml
  type-aliases-package: com.lijinghai.pojo


# 这里不能直接logging.level = info,debug等
logging:
  level:
    root: info
    com.lijinghai.mapper: debug
